version: '3.3'

services:
  api-parse-server:
    build: .
    container_name: api-parse-server
    platform: linux/x86_64
    mem_limit: “3g”
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
    env_file:
      - ./.env 
    networks:
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-parse-server.entrypoints=http"
      - "traefik.http.routers.api-parse-server.rule=Host(`${APP_PARSE_URL}`)"
      - "traefik.http.routers.api-parse-server-secure.entrypoints=https"
      - "traefik.http.routers.api-parse-server-secure.rule=Host(`${APP_PARSE_URL}`)"
      - "traefik.http.routers.api-parse-server-secure.tls=true"
      - "traefik.http.routers.api-parse-server-secure.tls.certresolver=http"
      - "traefik.http.routers.api-parse-server-secure.service=api-parse-server"
      - "traefik.http.services.api-parse-server.loadbalancer.server.port=${APP_PARSE_PORT}"
      - "traefik.docker.network=proxy"
      # middleware assignment
      - "traefik.http.routers.api-parse-server.middlewares=https-redirect@file"


  parse-dashboard:
    image: parseplatform/parse-dashboard:latest
    container_name: parse-dashboard
    platform: linux/x86_64
    command: 
      - parse-dashboard --dev
    environment:
      - PARSE_DASHBOARD_ALLOW_INSECURE_HTTP=1
    mem_limit: “3g”
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
    networks:
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./dashboard-config/parse-dashboard-config.json:/src/Parse-Dashboard/parse-dashboard-config.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.parse-dashboard.entrypoints=http"
      - "traefik.http.routers.parse-dashboard.rule=Host(`${APP_PARSE_DASHBOARD_URL}`)"
      - "traefik.http.routers.parse-dashboard-secure.entrypoints=https"
      - "traefik.http.routers.parse-dashboard-secure.rule=Host(`${APP_PARSE_DASHBOARD_URL}`)"
      - "traefik.http.routers.parse-dashboard-secure.tls=true"
      - "traefik.http.routers.parse-dashboard-secure.tls.certresolver=http"
      - "traefik.http.routers.parse-dashboard-secure.service=parse-dashboard"
      - "traefik.http.services.parse-dashboard.loadbalancer.server.port=${APP_PARSE_DASHBOARD_PORT}"
      - "traefik.docker.network=proxy"
      # middleware assignment
      - "traefik.http.routers.parse-dashboard.middlewares=https-redirect@file"
    depends_on:
      - parse-server-api

networks:
  proxy:
    external: true

  

