version: '3.8'

services:
  parse-server-api:
    build: .
    ports:
      - 3000:3000
    environment:
      - DATABASE_URI=postgres://postgres:samplepassword@db:5432/parse-sdk
      - APP_ID=template_baas_parse
      - MASTER_KEY=MasterKey
      - SERVER_URL=http://localhost:3000/parse # TOFIX: temporaryly use localhost:3000 until finds a better approach for local deployment
      - APP_NAME=Template BaaS Parse
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.parse-server-api.rule=Host(`api.localhost`)"
      - "traefik.http.routers.parse-server-api.entrypoints=http"
      - "traefik.http.middlewares.parse-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.parse.middlewares=parse-https-redirect"
      - "traefik.http.routers.parse-secure.rule=Host(`api.parse-template.com`)"
      - "traefik.http.routers.parse-secure.entrypoints=https"
      - "traefik.http.routers.parse-secure.tls=true"
      - "traefik.http.services.parse.loadbalancer.server.port=3000"
    depends_on:
      - traefik
      - db
  db:
    image: postgres
    container_name: parse-server-postgres
    environment:
      - POSTGRES_PASSWORD=samplepassword
      - POSTGRES_USER=sampleuser
      - POSTGRES_DB=parse-sdk
    volumes:
      - parse-server-postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  parse-dashboard:
    image: parseplatform/parse-dashboard:latest
    environment:
      - PARSE_DASHBOARD_ALLOW_INSECURE_HTTP=1
    command: 
      - parse-dashboard --dev
    ports:
      - "4040:4040"
    volumes:
      - ./config/parse-dashboard-config.json:/src/Parse-Dashboard/parse-dashboard-config.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.parse-dashboard.rule=Host(`dashboard.localhost`)"
      - "traefik.http.routers.parse-dashboard.entrypoints=http"
      - "traefik.http.middlewares.dashboard-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.dashboard.middlewares=dashboard-https-redirect"
      - "traefik.http.routers.dashboard-secure.rule=Host(`dashboard.parse-template.com`)"
      - "traefik.http.routers.dashboard-secure.entrypoints=https"
      - "traefik.http.routers.dashboard-secure.tls=true"
      - "traefik.http.services.dashboard.loadbalancer.server.port=4040"
    depends_on:
      - parse-server-api
      - traefik
  traefik:
    image: traefik:v2.9
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: unless-stopped
volumes:
  parse-server-postgres:

