version: '3.8'

services:
  parse-server-api:
    build: .
    ports:
      - 3000:3000
    environment:
      - DATABASE_URI=postgres://postgres:samplepassword@db:5432/parse-sdk
      - APP_ID=template_baas_parse
      - MASTER_KEY=MasterKey
      - SERVER_URL=http://localhost:3000/parse # TOFIX: temporaryly use localhost:3000 until finding a better approach for local deployment
      - APP_NAME=Template BaaS Parse
  db:
    image: postgres
    container_name: parse-server-postgres
    environment:
      - POSTGRES_PASSWORD=samplepassword
      - POSTGRES_USER=sampleuser
      - POSTGRES_DB=parse-sdk
    volumes:
      - parse-server-postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  parse-server-postgres:

